<h1>Summary</h1>

<h4>Decision Function(決定関数)</h4>
・2クラス分類の場合<br>
⇒<br>
decision_functionの結果の配列は(n_samples,)の形になり、サンプルごとに一つの浮動小数点が返される<br>
値が正であれば陽性クラスを、負であれば陰性（つまり陽性以外）クラスを意味する<br>
decision_functionのレンジは決まっておらず、データとモデルパラメータに依存するため、どのようなスケールで結果が表示されるかわからず解釈が難しい<br>
・多クラス分類の場合<br>
⇒<br>
decision_funcitonの結果の配列は(n_samples, n_classes)の形になる<br>
各列は個々のクラスに対する「確信度スコア」で、大きいとそのクラスである可能性が高く、小さくなると可能性が低くなる。各データポイントに対して、確信度スコアが最大になるクラスを選ぶことで予測クラスが得られる<br>

<h4>predict proba</h4>
・2クラス分類の場合<br>
⇒<br>
predict_probaの出力は、それぞれのクラスに属する確率で、decision_functionの出力よりも理解しやすい<br>
出力配列の形は、2クラス分類問題では、常に(n_samples, 2)になる<br>
各行の第一エントリは第一クラスの予測確率で、第二エントリは第二クラスの予測確率である。確率なので、predict_probaの出力は常に0から1であり、双方の和は常に1になっている<br>
2つのクラスの確率の和が1なので、どちらかが50%以上の確率（確信度）になっており、そのクラスが予測クラスになる<br>
・多クラス分類の場合<br>
⇒<br>
predict_probaの出力も、decision_functionと同じで、(n_samples, n_classes)の形の配列となる<br>
各クラスになる確率の和は1になる<br>
<br>
※注意<br>
predictで得られた結果をdecision_functionやpredict_probaで得られた結果と比較する際には、クラスが文字列だったり等、0から始まる整数で表現されていない場合には、クラス分類器のclasses_属性を使って、実際のクラス名を使うようにしなければならない

<h1>2クラス分類の場合</h1>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
%matplotlib inline

In [2]:
from sklearn.datasets import make_circles

In [3]:
X, y = make_circles(noise = 0.25, factor = 0.5, random_state = 1)
y_named = np.array(["blue", "red"])[y]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train_named, y_test_named, y_train, y_test = train_test_split(X , y_named, y, random_state = 0)

In [6]:
from sklearn.ensemble import GradientBoostingClassifier

In [7]:
gbrt = GradientBoostingClassifier(random_state = 0).fit(X_train, y_train_named)

In [8]:
decision_function = gbrt.decision_function(X_test)
decision_function

array([ 4.13592603, -1.70169917, -3.95106099, -3.62609552,  4.28986642,
        3.66166081, -7.69097179,  4.11001686,  1.10753937,  3.40782222,
       -6.46255955,  4.28986642,  3.90156346, -1.20031247,  3.66166081,
       -4.17231157, -1.23010079, -3.91576223,  4.03602783,  4.11001686,
        4.11001686,  0.65709014,  2.69826265, -2.65673274, -1.86776596])

In [9]:
gbrt.classes_

array(['blue', 'red'], dtype='<U4')

In [10]:
pred = gbrt.classes_[(decision_function > 0).astype(int)]
pred

array(['red', 'blue', 'blue', 'blue', 'red', 'red', 'blue', 'red', 'red',
       'red', 'blue', 'red', 'red', 'blue', 'red', 'blue', 'blue', 'blue',
       'red', 'red', 'red', 'red', 'red', 'blue', 'blue'], dtype='<U4')

In [11]:
np.all(pred == gbrt.predict(X_test))

True

In [12]:
print(f"Decision function minimum: {np.min(decision_function): .2f}")
print(f"Decision function maximum: {np.max(decision_function): .2f}")

Decision function minimum: -7.69
Decision function maximum:  4.29


In [13]:
predict_proba = gbrt.predict_proba(X_test)
predict_proba

array([[1.57362639e-02, 9.84263736e-01],
       [8.45756526e-01, 1.54243474e-01],
       [9.81128693e-01, 1.88713075e-02],
       [9.74070327e-01, 2.59296728e-02],
       [1.35214212e-02, 9.86478579e-01],
       [2.50463747e-02, 9.74953625e-01],
       [9.99543275e-01, 4.56725221e-04],
       [1.61426376e-02, 9.83857362e-01],
       [2.48329911e-01, 7.51670089e-01],
       [3.20518935e-02, 9.67948107e-01],
       [9.98441637e-01, 1.55836338e-03],
       [1.35214212e-02, 9.86478579e-01],
       [1.98099245e-02, 9.80190075e-01],
       [7.68580365e-01, 2.31419635e-01],
       [2.50463747e-02, 9.74953625e-01],
       [9.84817480e-01, 1.51825198e-02],
       [7.73836215e-01, 2.26163785e-01],
       [9.80463909e-01, 1.95360915e-02],
       [1.73607896e-02, 9.82639210e-01],
       [1.61426376e-02, 9.83857362e-01],
       [1.61426376e-02, 9.83857362e-01],
       [3.41393574e-01, 6.58606426e-01],
       [6.30759509e-02, 9.36924049e-01],
       [9.34424749e-01, 6.55752512e-02],
       [8.661995

In [14]:
predict_proba.sum(axis = 1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

<h1>多クラス分類の場合</h1>

In [15]:
from sklearn.datasets import load_iris

In [16]:
iris = load_iris()

In [17]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state = 42)

In [18]:
gbrt = GradientBoostingClassifier(learning_rate = 0.01, random_state = 0).fit(X_train, y_train)

In [19]:
decision_function = gbrt.decision_function(X_test)
decision_function

array([[-1.995715  ,  0.04758267, -1.92720695],
       [ 0.06146394, -1.90755736, -1.92793758],
       [-1.99058203, -1.87637861,  0.09686725],
       [-1.995715  ,  0.04758267, -1.92720695],
       [-1.99730159, -0.13469108, -1.20341483],
       [ 0.06146394, -1.90755736, -1.92793758],
       [-1.995715  ,  0.04758267, -1.92720695],
       [-1.99677434, -1.87637861,  0.09686725],
       [-1.995715  ,  0.04758267, -1.92720695],
       [-1.995715  ,  0.04758267, -1.92720695],
       [-1.99677434, -1.87637861,  0.07863156],
       [ 0.06146394, -1.90755736, -1.92793758],
       [ 0.06146394, -1.90755736, -1.92793758],
       [ 0.06146394, -1.90755736, -1.92793758],
       [ 0.06146394, -1.90755736, -1.92793758],
       [-1.995715  ,  0.04758267, -1.92720695],
       [-1.99087515, -1.87637861,  0.09686725],
       [-1.995715  ,  0.04758267, -1.92720695],
       [-1.995715  ,  0.04758267, -1.92720695],
       [-1.99087515, -1.87637861,  0.09686725],
       [ 0.06146394, -1.90755736, -1.927

In [20]:
np.all(np.argmax(decision_function, axis = 1) == gbrt.predict(X_test))

True

In [21]:
predict_proba = gbrt.predict_proba(X_test)
predict_proba

array([[0.10217718, 0.78840034, 0.10942248],
       [0.78347147, 0.10936745, 0.10716108],
       [0.09818072, 0.11005864, 0.79176065],
       [0.10217718, 0.78840034, 0.10942248],
       [0.10360005, 0.66723901, 0.22916094],
       [0.78347147, 0.10936745, 0.10716108],
       [0.10217718, 0.78840034, 0.10942248],
       [0.09763381, 0.11012538, 0.79224081],
       [0.10217718, 0.78840034, 0.10942248],
       [0.10217718, 0.78840034, 0.10942248],
       [0.09905185, 0.11172485, 0.78922331],
       [0.78347147, 0.10936745, 0.10716108],
       [0.78347147, 0.10936745, 0.10716108],
       [0.78347147, 0.10936745, 0.10716108],
       [0.78347147, 0.10936745, 0.10716108],
       [0.10217718, 0.78840034, 0.10942248],
       [0.09815477, 0.1100618 , 0.79178343],
       [0.10217718, 0.78840034, 0.10942248],
       [0.10217718, 0.78840034, 0.10942248],
       [0.09815477, 0.1100618 , 0.79178343],
       [0.78347147, 0.10936745, 0.10716108],
       [0.10178234, 0.11626145, 0.78195621],
       [0.

In [22]:
np.sum(predict_proba,axis = 1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [23]:
np.all(np.argmax(predict_proba, axis = 1) == gbrt.predict(X_test))

True

In [24]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [25]:
named_target = iris.target_names[y_train]

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
logreg = LogisticRegression().fit(X_train, named_target)

In [28]:
decision_function = logreg.decision_function(X_test)
decision_function

array([[ -3.03499321,   2.29425248,   0.74074073],
       [  5.91897443,   3.09086203,  -9.00983646],
       [-10.05185482,   1.8745736 ,   8.17728122],
       [ -2.7327919 ,   2.03622628,   0.69656562],
       [ -3.73730761,   2.475568  ,   1.2617396 ],
       [  6.03557963,   3.03459875,  -9.07017838],
       [ -0.28246979,   2.17692712,  -1.89445733],
       [ -5.08438189,   1.70755665,   3.37682525],
       [ -3.45483147,   2.35294938,   1.10188209],
       [ -1.14537934,   2.34758244,  -1.2022031 ],
       [ -4.54163979,   1.696957  ,   2.84468279],
       [  6.42918453,   3.10051706,  -9.52970159],
       [  6.75151419,   3.24338038,  -9.99489456],
       [  6.24916678,   3.09796127,  -9.34712805],
       [  6.61880949,   2.83424536,  -9.45305485],
       [ -3.046041  ,   1.94572148,   1.10031951],
       [ -6.55404992,   1.46148012,   5.0925698 ],
       [ -1.15322751,   2.38303184,  -1.22980433],
       [ -2.51135658,   2.0641394 ,   0.44721718],
       [ -6.23295266,   1.51653

In [29]:
pred = logreg.classes_[np.argmax(decision_function, axis = 1)]
pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa'], dtype='<U10')

In [30]:
np.all(pred == logreg.predict(X_test))

True